### ISSUE TITLE
Listener crashes during partial buffer dump

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/athomehub#14]
Device buffer dump has invalid value at position 12
Saving partial device buffer dump
Device buffer dump has invalid value at position 6
Saving partial device buffer dump
Device buffer dump has invalid value at position 17
Saving partial device buffer dump
Saving partial device buffer dump
Device buffer dump has invalid value at position 9
Saving partial device buffer dump
# <NoMethodError: undefined method `hex' for nil:NilClass>

/home/hubuser/athomehub/lib/hub_listener.rb:319:in `handleDump'
    /home/hubuser/athomehub/lib/hub_listener.rb:397:in`handle'
    /home/hubuser/athomehub/lib/hub_listener.rb:58:in `start'
    /home/hubuser/athomehub/lib/hub_listener.rb:502:in`listen'
    /home/hubuser/athomehub/lib/hub_listener.rb:491:in `each'
    /home/hubuser/athomehub/lib/hub_listener.rb:491:in`listen'
    /home/hubuser/athomehub/lib/hub_listener.rb:58:in `start'
    /home/hubuser/athomehub/lib/tasks/listener.rake:18
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`call'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`each'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in`invoke_with_call_chain'
    /usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in`invoke_task'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
    /usr/bin/rake:19:in `load'
    /usr/bin/rake:19
(in /home/hubuser/athomehub)

Saving partial device buffer dump
Device buffer dump has invalid value at position 19
Saving partial device buffer dump
Saving partial device buffer dump
# <NoMethodError: undefined method `hex' for nil:NilClass>

/home/hubuser/athomehub/lib/hub_listener.rb:328:in `handleDump'
    /home/hubuser/athomehub/lib/hub_listener.rb:397:in`handle'
    /home/hubuser/athomehub/lib/hub_listener.rb:58:in `start'
    /home/hubuser/athomehub/lib/hub_listener.rb:502:in`listen'
    /home/hubuser/athomehub/lib/hub_listener.rb:491:in `each'
    /home/hubuser/athomehub/lib/hub_listener.rb:491:in`listen'
    /home/hubuser/athomehub/lib/hub_listener.rb:58:in `start'
    /home/hubuser/athomehub/lib/tasks/listener.rake:18
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`call'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`each'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in`invoke_with_call_chain'
    /usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in`invoke_task'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
    /usr/bin/rake:19:in `load'
    /usr/bin/rake:19
(in /home/hubuser/athomehub)

Device buffer dump has invalid value at position 9
Saving partial device buffer dump
Device buffer dump has illegal sequence number 515
# <NoMethodError: undefined method `hex' for nil:NilClass>

/home/hubuser/athomehub/lib/hub_listener.rb:336:in `handleDump'
    /home/hubuser/athomehub/lib/hub_listener.rb:397:in`handle'
    /home/hubuser/athomehub/lib/hub_listener.rb:58:in `start'
    /home/hubuser/athomehub/lib/hub_listener.rb:502:in`listen'
    /home/hubuser/athomehub/lib/hub_listener.rb:491:in `each'
    /home/hubuser/athomehub/lib/hub_listener.rb:491:in`listen'
    /home/hubuser/athomehub/lib/hub_listener.rb:58:in `start'
    /home/hubuser/athomehub/lib/tasks/listener.rake:18
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`call'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`each'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in`invoke_with_call_chain'
    /usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in`invoke_task'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
    /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
    /usr/bin/rake:19:in `load'
    /usr/bin/rake:19
(in /home/hubuser/athomehub)

**Comment by dkirkby** [comment]
This bug has been fixed and the listener now has a general rescue clause when handling messages.
